### ISSUE TITLE
Platforms in `Next Generation Sequencing spreadsheet - T.tsv`

### ISSUE THREAD

**Issue by ay-amityadav** [crazyhottommy/getting-started-with-genomics-tools-and-resources#14]
First of all thanks for compiling this list `Next Generation Sequencing spreadsheet - T.tsv`!

This file contains three platforms: `Illumina PacBio RSII`, `Illumina PacBio Sequel 16cells v6.0 2018` and `Illumina PacBio Q1 2019`. With a limited search on Google, I didn't find any information about these platforms. What I have come to know is that `Illumina` and `PacBio` are two different companies. Can you please provide me any pointers/links for these platforms?

Thank you!

**Comment by crazyhottommy** [comment]
sorry, I missed this issue. I got the file from @avilella

**Comment by ay-amityadav** [comment]
Thanks!
This fork https://github.com/AllanSSX/developments-in-next-generation-sequencing of original repository contains updated information.

**Comment by avilella** [comment]
I don't have an equivalent to the plot with the instrument pictures, but
up-to-date info is at bit.ly/ngsspecs . For full product map of Illumina,
see tabs further to the right.

**Comment by ay-amityadav** [comment]
Thanks @avilella !
